### PR TITLE
Add missing dependency

### PR DESCRIPTION
**Pull request by Edu4rdSHL**
- It was discover while packaging the tool for BlackArch Linux.

### CODE REVIEW

**Comment by bannsec** [comment]
Strange that it's not happening on ubuntu. Can you post the packaging error
trace?

**Comment by Edu4rdSHL** [comment]
Yeah, see:

```
Traceback (most recent call last):
  File "/usr/bin/stegoveritas", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pfp' distribution was not found and is required by stegoveritas
```

**Comment by Edu4rdSHL** [comment]
Also, JFYI, the tool was packaged for BlackArch Linux: https://github.com/BlackArch/blackarch/blob/master/packages/stegoveritas/PKGBUILD

**Comment by noraj** [comment]
@bannsec Yeah @Edu4rdSHL and me packaged stegoveritas for blackarch (https://github.com/BlackArch/blackarch/issues/2302).

**Comment by bannsec** [comment]
Trying to figure out why your distro is having that issue specifically while Debian/Fedora don't. I had explicitly removed pfp as a install requirement since it creates a dependency loop that cannot currently be fixed. From the setup.py file:

```
 14 # TODO: Get 'six' package up to newest version. Right now py010parser is forcing it to 1.10.0, which isn't great.
 15 # NOTE: Removing pfp package for now, until I need it. If I do end up needing it, i will need to have my own versions of both pfp and py010parser
 16 # Specifically, I need to modify py010parser to not be stuck with an old "six" version (which is causing issues), then updated pfp to point to my version of py010parser.
 17 # https://github.com/d0c-s4vage/py010parser/pull/19
```

When packages lock in specific versions, then don't update those packages anymore, a LOT of dependency breaking happens. This is why I end up with `stegoveritas-<x>` packages...

In this case, pfp ends up requiring py010parser, which requires explicitly `six` version `1.10.0` which if i recall is too old of a `six` version for a different requirement.

Can you let me know where pfp is being required? I just tried again on a fresh python3.7 environment, and my code does not seem to reference pfp, and i don't appear to end up requiring or installing it.

**Comment by bannsec** [comment]
Ok, so i've deployed the custom stegoveritas version of those packages. I have the net setup in dev branch. Can you give that a build and let me know if it solves your issue?

**Comment by Edu4rdSHL** [comment]
This issue was solved long time ago, I forget to close it. Thank you!

**Pull request closed without merging**
